apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx:mainline
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config-volume
      restartPolicy: Always
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
status: {}
